/// Defines the primary category for every knowledge record in Neptune.
///
/// Every knowledge item in the system belongs to one category.
/// This allows searching, filtering and AI reasoning across the
/// complete Neptune Knowledge Repository.
enum KnowledgeCategory {
  species,
  bait,
  trace,
  rig,
  knot,
  hook,
  sinker,
  line,
  leader,
  swivel,
  lure,
  technique,
  baitPresentation,
  castingTechnique,
  beach,
  estuary,
  reef,
  riverMouth,
  structure,
  marine,
  weather,
  tides,
  lunar,
  safety,
  equipment,
  electronics,
  conservation,
  regulations,
  competition,
  fishBehaviour,
  fishAnatomy,
  fishCare,
  navigation,
  firstAid,
  travel,
  camping,
  cooking,
  maintenance,
  glossary,
}